language: node_js
node_js: stable
install:
  - npm ci
script:
  - npm run build
  - npm test
deploy:
  provider: pages
  local-dir: ./build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
